import { List } from '@mantine/core';
import React from 'react';

const TermsAndConditionsContent = () => (
  <div className="px-5 max-h-[500px] overflow-y-auto">
    <h2 className="text-center font-bold mb-5 border-b border-black mt-3 pb-2">TERMS OF USE</h2>
    <h3 className="text-center font-bold italic mb-5">Welcome to Adarth’s Terms of Use</h3>

    <section className="mb-5">
      <p className="mb-5">
        This legal agreement is an electronic record in terms of the{' '}
        <span className="font-bold">Information Technology Act, 2000</span> and rules there under as
        Applicable and the amended provisions about electronic records in various statutes as
        amended by the <span className="font-bold">Information Technology Act, 2000.</span> This
        electronic record is generated by a computer system and does not require any physical or
        digital signatures.
      </p>
      <p className="mb-5">
        This legal document is published in accordance with the provisions of{' '}
        <span className="font-bold">Rule 3 (1)</span> of the{' '}
        <span className="font-bold">
          Information Technology (Intermediaries guidelines) Rules, 2011
        </span>{' '}
        and <span className="font-bold">Rule 4</span> of the{' '}
        <span className="font-bold">
          Information Technology (Reasonable security practices and procedures and sensitive
          personal data or information) Rules, 2011
        </span>{' '}
        of <span className="font-bold">Information Technology Act, 2000</span> amended through{' '}
        <span className="font-bold">Information Technology Amendment Act, 2008</span> that require
        publishing the Terms of Use and practices for access and usage of any functional
        Application.
      </p>
      <p className="mb-5">
        This Application is created and operated by{' '}
        <span className="font-bold">M/s Adarth Private Limited,</span> having its registered office
        at{' '}
        <span className="font-bold">
          208, 2ND FLOOR, DLF STAR TOWER, SECTOR - 30 GURGAON, HR- 122001
        </span>
        (hereinafter referred to as “We”, “Our”, and “Us ).We intend to ensure your steady
        commitment to the usage of this Application and the services provided by us through our
        Application.
      </p>
      <p>
        For the purpose of these Terms of Use (<span className="font-bold">“Terms of Use”</span>),
        wherever the context so requires, “We”, “Our”, and “Us” shall mean and refer to the
        Application. “You”, “Your”, “Yourself”, “User” shall mean and refer to natural and legal
        individuals who shall be users of this Application provided by us and who is competent to
        enter into binding contracts, as per law. “Third Parties” refer to any Application, platform
        or individual apart from the Users and the creator of this Application.
      </p>
    </section>

    <section className="mb-5">
      <h2 className="text-center font-bold">GENERAL TERMS</h2>
      <List type="ordered" withPadding listStyleType="disc">
        <List.Item>
          The headings of each section in these Terms of Use are only for the purpose of organizing
          the various provisions under these Terms of Use in an orderly manner and shall be used by
          you to interpret the provisions contained herein in a manner as may Apply to you. Further,
          it is specifically agreed by you that the headings shall have legal or contractual value
          on your usage of the Application.
        </List.Item>
        <List.Item>
          The use of this Application is solely governed by these Terms of Use, Privacy Policy that
          may be uploaded on the Application and any modifications or amendments made thereto by us
          from time to time, at our sole discretion. If you as a user continue to access and use
          this Application, you are agreeing to comply with and be bound by the following Terms of
          Use and Privacy Policy.
        </List.Item>
        <List.Item>
          You expressly agree and acknowledge that these Terms of Use and Privacy Policy are
          co-terminus in nature and that expiry/termination of either one will lead to the
          termination of the other.
        </List.Item>
        <List.Item>
          You unequivocally agree that these Terms of Use and the Privacy Policy constitute a
          legally binding agreement between us, and that you shall be subject to the rules,
          guidelines, policies, terms, and conditions Applicable to your use of the Application, and
          that the same shall be deemed to be incorporated into these Terms of Use and shall be
          treated as part and parcel of the same. You acknowledge and agree that no signature or
          express act is required to make these Terms of Use and the Privacy Policy binding on you
          and that your act of visiting any part of the Application constitutes your full and final
          acceptance of these Terms of Use and the Privacy Policy.
        </List.Item>
        <List.Item>
          We reserve the sole and exclusive right to amend or modify these Terms of Use without any
          prior permission or intimation to you, and you expressly agree that any such amendments or
          modifications shall come into effect immediately. If you do not adhere to the changes, you
          must stop using the Application at once. Your continued use of the Application will
          signify your acceptance of the changed terms.
        </List.Item>
      </List>
    </section>

    <section className="mb-5">
      <h2 className="text-center font-bold">PLATFORM OVERVIEW</h2>
      <p>
        This Platform allows the user to avail the services offered by{' '}
        <span className="font-bold italic">Adarth Application</span> at a single click.
        <span className="font-bold italic">Adarth</span> is a one-stop destination for your
        goal-focused OOH Campaigns. With a vision of connecting the fragmented OOH Industry,{' '}
        <span className="font-bold">Adarth</span>
        is a one-stop destination for your goal-focused OOH Campaigns. With a vision of connecting
        the fragmented OOH Industry, Adarth combines technology & people to create a well-defined
        structure for OOH. In the current chaotic & unorganized model of OOH Ads, it’s highly
        challenging for brands to book ad spaces without burning a lot of resources.{' '}
        <span className="font-bold italic">Adarth</span> helps media owners manage their inventories
        & operations easily.
      </p>
      <p>
        User has to register on the platform to avail the above mentioned services and the user in
        turn has to pay for these services offered.
      </p>
    </section>

    <section className="mb-5">
      <h2 className="text-center font-bold">REGISTRATION</h2>
      <p>The Users can register by providing the following information:</p>
      <List type="ordered" withPadding listStyleType="disc">
        <List.Item>Name</List.Item>
        <List.Item>Phone Number</List.Item>
        <List.Item>Email ID</List.Item>
        <List.Item>Address</List.Item>
        <List.Item>City</List.Item>
      </List>
      <p>Registration by linking any social media account is not allowed.</p>
    </section>

    <section className="mb-5">
      <h2 className="text-center font-bold">ELIGIBILITY</h2>
      <List type="ordered" withPadding listStyleType="disc">
        <List.Item>
          You represent and warrant that you are competent and eligible to enter into legally
          binding agreements and of age and that you have the requisite authority to bind yourself
          to these Terms of Use following the Law. However, if you are a minor using this
          Application, you may do so with the consent of your legal guardian. All Acts of minor
          shall be deemed to be considered as the acts undertaken under the supervision of their
          legal guardian.
        </List.Item>
        <List.Item>
          You further represent that you will comply with these Terms of Use and all Applicable
          local, state, national and international laws, rules and regulations.
        </List.Item>
        <List.Item>
          You shall not use the Application if you are not competent to contract or are disqualified
          from doing so by any other Applicable law, rule or regulation currently in force.
        </List.Item>
      </List>
      <p>Registration by linking any social media account is not allowed.</p>
    </section>

    <section className="mb-5">
      <h2 className="text-center font-bold">PAYMENT GATEWAY</h2>
      <p>
        For making all payments for services on the Application, you shall be required to make
        payment for which you will be redirected to a third-party payment gateway that we may have
        an agreement with. The payment gateway may additionally seek information from you to process
        the payment for your purchase and additionally may charge you the payment gateway charges
        that may be Applicationlicable. The payment gateway consists of Debit Card/Credit Card/Net
        Banking/UPI and other wallet options. You shall be governed under the concerned payment
        gateway’s Terms and Conditions and other Policies for the purpose of all payment-related
        aspects.
      </p>
    </section>

    <section className="mb-5">
      <h2 className="text-center font-bold">CONTENT</h2>
      <p className="mb-5">
        All text, graphics, User interfaces, visual interfaces, photographs, trademarks, logos,
        brand names, descriptions, sounds, music and artwork (collectively,{' '}
        <span className="font-bold">‘Content’</span>), is generated/provided or based on information
        provided by the users or third parties and We have no control and make no guarantees
        regarding the quality, the accuracy, integrity or genuineness of such content or such other
        information provided on the Application.
      </p>

      <p className="mb-5">
        All the Content displayed on the Application is subject to copyright and shall not be reused
        by You (or a third party) without the prior written consent from Us and the copyright owner.
      </p>

      <p className="mb-5">
        You are solely responsible for the integrity, authenticity, quality and genuineness of the
        content provided on the Application and whilst feedback and comments by You can be made via
        the Application, we bear no liability whatsoever for any feedback or comments made by the
        other Users or made in respect of any of the content on the Application. Further, the
        Application reserves its right to suspend the account of any User for an indefinite period
        to be decided at the discretion of the Application or to terminate the account of any User
        who is found to have created or shared or submitted any content or part thereof that is
        found to be untrue/inaccurate/misleading or offensive/vulgar. You shall be solely
        responsible for making good any financial or legal losses incurred through the
        creation/sharing/submission of Content or part thereof that is deemed to be
        untrue/inaccurate/misleading.
      </p>
      <p>
        You have a personal, non-exclusive, non-transferable, revocable, limited privilege to access
        the content on the Application. You shall not copy, adapt, and modify any content without
        written permission from Us.
      </p>
    </section>

    <section className="mb-5">
      <h2 className="text-center font-bold">INDEMNITY</h2>
      <p className="mb-5">
        You agree to indemnify, defend and hold harmless the Us, and our respective directors,
        officers, employees and agents (collectively,{' '}
        <span className="font-bold">&quot;Parties&quot;</span>), from and against any losses,
        liabilities, claims, damages, demands, costs and expenses (including legal fees and
        disbursements in connection therewith and interest chargeable thereon) asserted against or
        incurred by Us that arise out of, result from, or maybe payable by, any breach or
        non-performance of any representation, warranty, covenant or agreement made or obligation to
        be performed according to these Terms of Use. Further, You agree to hold the Us harmless
        against any claims made by any third party due to, or arising out of, or in connection with:
      </p>
      <List type="ordered" withPadding listStyleType="disc">
        <List.Item>Your use of the Application,</List.Item>
        <List.Item>Your violation of these Terms of Use;</List.Item>
        <List.Item>Your violation of any rights of another;</List.Item>
        <List.Item>Your alleged improper conduct according to these Terms of use;</List.Item>
        <List.Item>Your conduct in connection with the Application;</List.Item>
      </List>
      <p className="my-5">
        You agree to fully cooperate in indemnifying Us at your expense. You also agree not to
        settle with any party without consent from Us.
      </p>
      <p>
        In no event shall we be liable to compensate You or any third party for any special,
        incidental, indirect, consequential or punitive damages whatsoever, including those
        resulting from loss of use, data or profits, whether or not foreseeable, and whether or not
        You had been advised of the possibility of such damages, or based on any theory of
        liability, including breach of contract or warranty, negligence or other tortuous action, or
        any other claim arising out of or in connection with the Your use of or access to the
        Application and/or the Services or materials contained therein.
      </p>
    </section>

    <section className="mb-5">
      <h2 className="text-center font-bold">LIMITATION OF LIABILITY</h2>

      <List withPadding listStyleType="disc">
        <List.Item>
          We are not responsible for any consequences arising out of the following events:
          <List withPadding listStyleType="disc">
            <List.Item>
              If the Application is inoperative/non-responsive due to any connectivity errors
              associated with the internet connection such as but not limited to slow connectivity,
              no connectivity, server failure;
            </List.Item>
            <List.Item>
              If you have fed incorrect information or data or for any deletion of data;
            </List.Item>
            <List.Item>
              If there is an undue delay or inability to communicate through email;
            </List.Item>
            <List.Item>
              If there is any deficiency or defect in the Services managed by Us;
            </List.Item>
            <List.Item>
              If there is a failure in the functioning of any other service provided by Us.
            </List.Item>
          </List>
        </List.Item>

        <List.Item>
          The Application accepts no liability for any errors or omissions, on behalf of itself, or
          for any damage caused to You, your belongings, or any third party, resulting from the use
          or misuse of the Application or any service availed of by Us through the Application. The
          service and any Content or material displayed on the service is provided without any
          guarantees, conditions or warranties as to its accuracy, suitability, completeness or
          reliability. We will not be liable to you for the unavailability or failure of the
          Application.
        </List.Item>

        <List.Item>
          You are to comply with all laws Applicable to you or your activities, and with all
          Policies, which are hereby incorporated into this Terms of Use by reference.
        </List.Item>

        <List.Item>
          The Application expressly excludes any liability for any loss or damage that was not
          reasonably foreseeable by the Application and which is incurred by you in connection with
          the Application, including loss of profits; and any loss or damage incurred by you as a
          result of your breach of these Terms of Use.
        </List.Item>

        <List.Item>
          To the fullest extent permitted by law, we shall not be liable to You or any other party
          for any loss or damage, regardless of the form of action or basis of any claim. You
          acknowledge and agree that your sole and exclusive remedy for any dispute with us is to
          terminate your use of the Application.
        </List.Item>
      </List>
    </section>

    <section className="mb-5">
      <h2 className="text-center font-bold">TERM</h2>
      <List type="ordered" withPadding listStyleType="disc">
        <List.Item>
          These Terms of Use shall continue to form a valid and binding contract between us and
          shall continue to be in full force and effect until you continue to access and use the
          Applications.
        </List.Item>
        <List.Item>You may terminate your use of the Application at any time.</List.Item>
        <List.Item>
          We may terminate these Terms of Use and close your account at any time without notice
          and/or suspend or terminate Your access to the Application at any time and for any reason,
          if any discrepancy or legal issue arises.
        </List.Item>
        <List.Item>
          Such suspension or termination shall not limit our right to take any other action against
          you that we consider Appropriate.
        </List.Item>
        <List.Item>
          It is also hereby declared that we may discontinue the Services and Applications without
          any prior notice.
        </List.Item>
      </List>
    </section>

    <section className="mb-5">
      <h2 className="text-center font-bold">TERMINATION</h2>
      <List type="ordered" withPadding listStyleType="disc">
        <List.Item>
          We reserve the right, in its sole discretion, to unilaterally terminate Your access to the
          Application, or any portion thereof, at any time, without notice or cause.
        </List.Item>
        <List.Item>
          We also reserve the universal right to deny access to You, to any/all of are on its
          Application without any prior notice/explanation to protect the interests of the
          Application and/or other Users to the Application.
        </List.Item>
        <List.Item>
          We reserve the right to limit, deny or create different access to the Application and its
          features concerning different Users, or to change any of the features or introduce new
          features without prior notice.
        </List.Item>
        <List.Item>
          You shall continue to be bound by these Terms of use, and it is expressly agreed to by You
          that You shall not have the right to terminate these Terms of Use till the expiry of the
          same.
        </List.Item>
      </List>
    </section>

    <section className="mb-5">
      <h2 className="text-center font-bold">COMMUNICATION</h2>
      <p className="mb-5">
        By using this Application and providing Your identity and contact information to Us through
        the Application, You agree and consent to receive emails or SMS from Us and/or any of its
        representatives at any time.
      </p>
      <p className="mb-5">
        You can report to <span className="font-bold">“info@adarth.in”</span> if you find any
        discrepancy with regard to Application or content-related information and we will take
        necessary action after an investigation. The response with resolution (if any issues found)
        shall be dependent on the time taken for investigation.
      </p>
      <p className="mb-5">
        You expressly agree that notwithstanding anything contained hereinabove, it may be contacted
        by Us relating to any services availed by You on the Application or anything pursuant
        thereto and You agree to indemnify Us from any harassment claims. It is expressly agreed to
        by Us that any information shared by Us shall be governed by the Privacy Policy.
      </p>
    </section>

    <section className="mb-5">
      <h2 className="text-center font-bold">
        USER OBLIGATIONS AND FORMAL UNDERTAKINGS AS TO CONDUCT
      </h2>
      <p>You agree and acknowledge that you are a restricted user of this Application and you:</p>
      <List type="ordered" withPadding listStyleType="disc">
        <List.Item>
          Agree to provide genuine credentials during the process whenever required on the
          Application. You shall not use a fictitious identity. We are not liable if you have
          provided incorrect information.
        </List.Item>
        <List.Item>
          Agree to ensure the Name, Email address, Phone Number, and any such other information that
          may be provided and is valid at all times and shall keep your information accurate and
          up-to-date.
        </List.Item>
        <List.Item>
          You agree that You are solely responsible for maintaining the confidentiality of your
          account. You agree to notify us immediately of any unauthorized use of your account. We
          reserve the right to close your account at any time for any or no reason.
        </List.Item>
        <List.Item>
          You will only use the Service for Your personal use and will not resell or assign it to a
          third party.
        </List.Item>
        <List.Item>You will not use the Service or Application for unlawful purposes;</List.Item>
        <List.Item>
          You will provide such information and documents which are essential for the provision of
          service.
        </List.Item>
        <List.Item>You will only use a network that is authorized to avail the Service.</List.Item>
        <List.Item>
          You will comply with all Applicable Law from Your country of domicile and residence and
          the country, state and/or city in which You are present while using the Site or Service;
        </List.Item>
        <List.Item>
          You are aware of and shall comply with the Information Technology Act, 2000 and the rules,
          regulations and guidelines notified thereunder.
        </List.Item>
        <List.Item>
          You understand and acknowledge that the data submitted is manually entered into the
          database of the Application and the Company will not be responsible for leakage or breach
          of the same.
        </List.Item>
        <List.Item>
          The Customer takes the sole and absolute responsibilities of the quality or quantity of
          the Product. In case of any discrepancy, the Customer shall be solely liable.
        </List.Item>
        <List.Item>
          You authorize the Application to use, store or otherwise process certain personal
          information and all published Content, responses, locations, User comments, reviews and
          ratings for personalization of Services, marketing and promotional purposes and for
          optimization of User-related options and Services.
        </List.Item>
        <List.Item>
          Understand and agree that, to the fullest extent permissible by law, the Application or
          any of their affiliates or their respective officers, directors, employees, agents,
          licensors, representatives, operational service providers, advertisers or suppliers shall
          not be liable for any loss or damage, of any kind, direct or indirect, in connection with
          or arising from the use of the Application or this terms of use, including, but not
          limited to, compensatory, consequential, incidental, indirect, special or punitive
          damages.
        </List.Item>
        <List.Item>
          Are bound not to cut, copy, modify, recreate, reverse engineer, distribute, disseminate,
          post, publish or create derivative works from, transfer, or sell any information or
          obtained from the Application. Any such use/limited use of the Application will only be
          allowed with the prior express written permission.
        </List.Item>
        <List.Item>
          Agree not to access (or attempt to access) the Application and/or the materials or
          Services by any means other than through the interface provided by the Application. The
          use of deep-link, robot, spider or other automatic devices, program, algorithm or
          methodology, or any similar or equivalent manual process, to access, acquire, copy or
          monitor any portion of the Application or its content, or in any way reproduce or
          circumvent the navigational structure or presentation of the Application, materials or any
          content, or to obtain or attempt to obtain any materials, documents or information through
          any means not specifically made available through the Application will lead to suspension
          or termination of your access to the Application. We disclaim any liabilities arising
          concerning such offensive content on the Application.
        </List.Item>
        <List.Item>
          Expressly agree and acknowledge that the Content generated by the Users and displayed on
          the Application is not owned by Us and that We are in no way responsible for the content
          of the same. You may, however, report any offensive or objectionable content, which We may
          then remove from the Application, at our sole discretion.
        </List.Item>
      </List>
      <p>You further undertake not to:</p>
      <List.Item>
        Engage in any activity that interferes with or disrupts access to the Application or the
        services provided therein (or the servers and networks which are connected to the
        Application);
      </List.Item>
      <List.Item>
        Impersonate any person or entity, or falsely state or otherwise misrepresent his/her
        affiliation with a person or entity;
      </List.Item>
      <List.Item>
        Probe, scan or test the vulnerability of the Application or any network connected to the
        Application, nor breach the security or authentication measures on the Application or any
        network connected to the Application. The User may not reverse look-up, trace or seek to
        trace any information relating to any other User of, or visitor to, the Application, or any
        other viewer of the Application, including any User account maintained on the Application
        not operated/managed by the User, or exploit the Application or information made available
        or offered by or through the Application, in any manner;
      </List.Item>
      <List.Item>
        Disrupt or interfere with the security of, or otherwise cause harm to, the Application,
        systems resources, accounts, passwords, servers, or networks connected to or accessible
        through the Application or any affiliated or linked Applications.
      </List.Item>
      <List.Item>
        Use the Application or any material or content therein for any purpose that is unlawful or
        prohibited by these Terms of Use, or to solicit the performance of any illegal activity or
        other activity which infringes the rights of this Application or any other third party(s);
      </List.Item>
      <List.Item>
        Violate any code of conduct or guideline which may Apply for or to any particular service
        offered on the Application;
      </List.Item>
      <List.Item>
        Violate any Applicable laws, rules or regulations currently in force within or outside
        India;
      </List.Item>
      <List.Item>
        Violate any portion of these Terms of Use or the Privacy Policy, including but not limited
        to any Applicable additional terms of the Application contained herein or elsewhere, whether
        made by amendment, modification, or otherwise;
      </List.Item>
      <List.Item>
        Commit any act that causes Us to lose (in whole or in part) the Services of its Internet
        Establishment (<span className="font-bold">&quot;ISP&quot;</span>) or in any manner disrupts
        the Services of any other supplier/service provider of the Application;
      </List.Item>
      <List.Item>
        You hereby expressly authorize Us to disclose any and all information relating to You in our
        possession to law enforcement or other government officials, as We may in our sole
        discretion, believe necessary or Appropriate in connection with the investigation and/or
        resolution of possible crimes, especially those involve personal injury and
        theft/infringement of intellectual property. You further understand that the Application
        might be directed to disclose any information (including the identity of persons providing
        information or materials on the Application) as necessary to satisfy any judicial Order,
        law, regulation or valid governmental request.
      </List.Item>
      <List.Item>
        By indicating Your acceptance to use any services offered on the Application, You are
        obligated to complete such transactions after making payment. You shall be prohibited from
        indicating their acceptance to avail services where the transactions have remained
        incomplete.
      </List.Item>
      <List.Item>
        You agree to use the services provided by Us, our affiliates, consultants and contracted
        companies, for lawful purposes only.
      </List.Item>
      <List.Item>
        You agree to provide authentic and true information. We reserve the right to confirm and
        validate the information and other details provided by You at any point in time. If upon
        confirmation such details are found to be false, not to be true (wholly or partly), We shall
        in our sole discretion reject the order and debar You from using the Application without
        prior intimation whatsoever.
      </List.Item>
      <List.Item>
        You agree not to post any material on the Application that is defamatory, offensive,
        obscene, indecent, abusive, or needlessly distressful or advertising any goods or services.
        More specifically, you agree not to host, display, upload, update, publish, modify,
        transmit, or in any manner share any information that:
        <List withPadding listStyleType="disc">
          <List.Item>belongs to another person and to which you have no right to;</List.Item>
          <List.Item>
            is grossly harmful, harassing, blasphemous, defamatory, obscene, pornographic,
            pedophilic, libelous, invasive of another&apos;s privacy, hateful, or racially,
            ethnically objectionable, disparaging, relating or encouraging money laundering or
            gambling, or otherwise unlawful in any manner whatever;
          </List.Item>
          <List.Item>is in any way harmful to minors;</List.Item>
          <List.Item>
            infringes any patent, trademark, copyright or other proprietary rights;
          </List.Item>
          <List.Item>violates any law for the time being in force;</List.Item>
          <List.Item>
            deceives or misleads the addressee about the origin of such messages or communicates any
            information which is grossly offensive or menacing;
          </List.Item>
          <List.Item>
            Abuse, harass, threaten, defame, disillusion, erode, abrogate, demean or otherwise
            violate the legal rights of others;
          </List.Item>
          <List.Item>
            Impersonate any person or entity, or falsely state or otherwise misrepresent Your
            affiliation with a person or entity;
          </List.Item>
          <List.Item>
            Publish, post, disseminate, any grossly harmful information, harassing, blasphemous,
            defamatory, obscene, pornographic, pedophilic, libellous, invasive of another&apos;s
            privacy, hateful, or racially, ethnically objectionable, disparaging, relating or
            encouraging money laundering or gambling, or otherwise unlawful in any manner whatever;
            or unlawfully threatening or unlawfully harassing including but not limited to
            &quot;indecent representation of women&quot; within the meaning of the Indecent
            Representation of Women (Prohibition) Act, 1986;
          </List.Item>
          <List.Item>
            Threatens the unity, integrity, defense, security or sovereignty of India, friendly
            relations with foreign states, or public order or causes incitement to the commission of
            any cognizable offense or prevents investigation of any offense or is insulting any
            other nation.
          </List.Item>
        </List>
      </List.Item>
    </section>

    <section className="mb-5">
      <h2 className="text-center font-bold">SUSPENSION OF USER ACCESS AND ACTIVITY</h2>
      <p>
        Notwithstanding other legal remedies that may be available, we may in our sole discretion,
        limit your access and/or activity by immediately removing your access credentials either
        temporarily or indefinitely, or suspend/terminate your association with the Application,
        and/or refuse to the usage of the Application, without being required to provide you with
        notice or cause:
      </p>
      <List type="ordered" withPadding listStyleType="disc">
        <List.Item>
          If you are in breach of any of these Terms of Use or the Privacy Policy;
        </List.Item>
        <List.Item>
          If you have provided wrong, inaccurate, incomplete or incorrect information;
        </List.Item>
        <List.Item>
          If your actions may cause any harm, damage or loss to the other Users or Us, at our sole
          discretion.
        </List.Item>
      </List>
    </section>

    <section className="mb-5">
      <h2 className="text-center font-bold">INTELLECTUAL PROPERTY RIGHTS</h2>
      <p className="mb-5">
        Unless expressly agreed to in writing, nothing contained herein shall give you a right to
        use any of the trade names, trademarks, service marks, logos, domain names, information,
        questions, answers, solutions, reports and other distinctive brand features, save according
        to the provisions of these Terms of Use that shall be available on the Application. All
        logos, trademarks, brand names, service marks, domain names, including material, designs,
        and graphics created by and developed by either the Application or such other third party
        and other distinctive brand features of the Application are the property of the Application
        or the respective copyright or trademark owner. Furthermore, concerning the Application, we
        shall be the exclusive owner of all the designs, graphics and the like, related to the
        Application.
      </p>
      <p className="mb-5">
        You shall not use any of the intellectual property displayed on the Application in any
        manner that is likely to cause confusion among existing or prospective users of the
        Application, or that in any manner disparages or discredits the Application, to be
        determined in the sole discretion.
      </p>
      <p className="mb-5">
        You are aware of all intellectual property, including but not limited to copyrights,
        relating to said services resides with the owners, and that at no point does any such
        intellectual property stand transferred from the aforementioned creators. We provide an
        option on the Application through which You can choose may or may not choose to communicate
        with other users and the Application does not own any of the intellectual property relating
        to the independent content displayed on the Application, apart from created graphics and
        specified content.
      </p>
      <p>
        You are further aware that any reproduction or infringement of the intellectual property of
        the aforementioned owners by You will result in legal action being initiated against You by
        the respective owners of the intellectual property so reproduced/infringed upon. It is
        agreed to by You that the contents of this section shall survive even after the termination
        or expiry of these Terms of Use and/or Privacy Policy.
      </p>
    </section>

    <section className="mb-5">
      <h2 className="text-center font-bold">DISCLAIMER OF WARRANTIES AND LIABILITIES</h2>
      <List type="ordered" withPadding listStyleType="disc">
        <List.Item>
          You further agree and undertake that you are accessing the Application at your sole risk
          and are using the best and prudent judgment before availing of any features on the
          Application or accessing/using any information displayed thereon.
        </List.Item>
        <List.Item>
          You agree that any kind of information, resources, activities, recommendations
          obtained/availed from the Application, written or oral, will not create any warranty and
          we disclaim all liabilities resulting from these.
        </List.Item>
        <List.Item>
          We do not guarantee that the features and content contained in the Application will be
          uninterrupted or error-free, or that the Application or its server will be free of viruses
          or other harmful components, and You hereby expressly accept any associated risks involved
          with your use of the Application.
        </List.Item>
        <List.Item>
          It is further agreed to by You that the contents of this section shall survive even after
          the termination or expiry of the Terms of Use and/or Privacy Policy.
        </List.Item>
      </List>
    </section>

    <section className="mb-5">
      <h2 className="text-center font-bold">FORCE MAJEURE</h2>
      <p>
        We will not be liable for damages for any delay or failure to perform our obligations
        hereunder if such delay or failure is due to cause beyond our control or without its fault
        or negligence, due to Force Majeure events including but not limited to acts of war, acts of
        God, earthquake, riot, fire, festive activities sabotage, labor shortage or dispute,
        internet interruption, technical failure, breakage of sea cable, hacking, piracy, cheating,
        illegal or unauthorized.
      </p>
    </section>

    <section className="mb-5">
      <h2 className="text-center font-bold">DISPUTE RESOLUTION AND JURISDICTION</h2>
      <p className="mb-5">
        In the event of any dispute arising out of or in connection with this agreement, including
        any dispute relating to the validity of this agreement, the parties shall, at first
        instance, attempt to resolve the dispute by mediation administered by the Centre for Online
        Resolution of Disputes (“CORD”) (<span className="underline">www.resolveoncord.com</span>)
        and conducted in accordance with the CORD Rules of Mediation, by a sole mediator to be
        Applicationointed by CORD.
      </p>
      <p className="mb-5">
        In the event the parties are unable to resolve any such dispute through mediation within 45
        days of the initiation of the dispute, subject to a contrary agreement between the parties,
        the dispute shall be finally resolved by arbitration administered by CORD and conducted in
        accordance with the Rules of Arbitration of CORD, by a sole arbitrator to be
        Applicationointed by CORD. The language of the arbitration shall be English. The seat of
        arbitration shall be
        <span className="font-bold">Haryana, India.</span>
      </p>
      <p>
        You expressly agree that the Terms of Use, Privacy Policy and any other agreements entered
        into between the Parties are governed by the laws, rules, and regulations of India.
      </p>
    </section>

    <section className="mb-5">
      <h2 className="text-center font-bold">MISCELLANEOUS PROVISIONS</h2>
      <List type="ordered" withPadding listStyleType="disc">
        <List.Item>
          <span className="font-bold">Entire Agreement:</span> These Terms of Use, read with the
          Privacy Policy, form the complete and final contract between us with respect to the
          subject matter hereof and supersedes all other communications, representations, and
          agreements (whether oral, written or otherwise) relating thereto.
        </List.Item>
        <List.Item>
          <span className="font-bold">Waiver:</span> The failure at any time to require performance
          of any provision of these Terms of Use shall in no manner affect our right at a later time
          to enforce the same. No waiver by us of any breach of these Terms of Use, whether by
          conduct or otherwise, in any one or more instances, shall be deemed to be or construed as
          a further or continuing waiver of any such breach, or a waiver of any other breach of
          these Terms of Use.
        </List.Item>
        <List.Item>
          <span className="font-bold">Severability:</span> If any provision/clause of these Terms of
          Use is held to be invalid, illegal or unenforceable by any court or authority of competent
          jurisdiction, the validity, legality, and enforceability of the remaining
          provisions/clauses of these Terms of Use shall in no way be affected or impaired thereby,
          and each such provision/clause of these Terms of Use shall be valid and enforceable to the
          fullest extent permitted by law. In such case, these Terms of Use shall be reformed to the
          minimum extent necessary to correct any invalidity, illegality or unenforceability, while
          preserving to the maximum extent the original rights, intentions and commercial
          expectations of the Parties hereto, as expressed herein.
        </List.Item>
        <List.Item>
          <span className="font-bold">Contact Us:</span> If you have any questions about these Terms
          of Use, the practices of the Application, or your experience, you can contact us by
          emailing us at <span className="underline text-blue-600">info@adarth.in</span> or by
          writing to us at
        </List.Item>
      </List>
      <h2 className="text-center font-bold">
        M/S ADARTH PRIVATE LIMITED 208, 2ND FLOOR, DLF STAR TOWER, SECTOR – 30, GURGAON, HARYANA-
        122001
      </h2>
    </section>
  </div>
);

export default TermsAndConditionsContent;
